In [1]:
import pandas as pd
import requests as req
import random

In [2]:
us_postal_codes = pd.io.parsers.read_csv('us_postal_codes.csv', dtype={'Zip Code': 'str'})

In [3]:
us_postal_codes_df = pd.DataFrame(us_postal_codes)
us_postal_codes_df.rename(columns = {"State.1": "State Abbreviation", "State Abbreviation": "County"}, inplace=True)
us_postal_codes_df.head()

,Zip Code,Place Name,State,State Abbreviation,County,Latitude,Longitude
0,00501,Holtsville,New York,NY,Suffolk,40.8154,-73.0451
1,00544,Holtsville,New York,NY,Suffolk,40.8154,-73.0451
2,01001,Agawam,Massachusetts,MA,Hampden,42.0702,-72.6227
3,01002,Amherst,Massachusetts,MA,Hampshire,42.3671,-72.4646
4,01003,Amherst,Massachusetts,MA,Hampshire,42.3919,-72.5248

In [4]:
# Lists for DataFrame
zip_code = []
place_name = []
state = []
state_abb = []
county = []
lat = []
lng = []

In [5]:
# Range of random numbers to chose from and list of random numbers used so far
a = range(40933)
rand_num = []

while len(zip_code) < 200:
    
    # Get a random index number
    b = a[random.randint(0,len(a))]

    if b in rand_num:
        continue
    else:
        city = us_postal_codes_df.iloc[b,:]
    
        # Appending data
        zip_code.append(city['Zip Code'])
        place_name.append(city['Place Name'])
        state.append(city['State'])
        state_abb.append(city['State Abbreviation'])
        county.append(city['County'])
        lat.append(city['Latitude'])
        lng.append(city['Longitude'])

In [6]:
cities = {
    "Zip Code": zip_code,
    "City Name": place_name,
    "State": state,
    "State Abbreviation": state_abb,
    "County": county,
    "Latitude": lat,
    "Longitude": lng
}

In [7]:
cities_df = pd.DataFrame(cities)

In [8]:
cities_df

,City Name,County,Latitude,Longitude,State,State Abbreviation,Zip Code
0,Morganton,Fannin,34.8714,-84.2115,Georgia,GA,30560
1,Dove Creek,Dolores,37.7632,-108.9181,Colorado,CO,81324
2,Belvue,Pottawatomie,39.2273,-96.1866,Kansas,KS,66407
3,New Berlin,Sangamon,39.7681,-89.8550,Illinois,IL,62670
4,Denver,Denver,39.6667,-105.0854,Colorado,CO,80227
5,Sunland,Los Angeles,34.2669,-118.3023,California,CA,91041
6,Charlotte,Mecklenburg,35.0869,-80.8167,North Carolina,NC,28226
7,Madawaska,Aroostook,47.3294,-68.3328,Maine,ME,04756
8,Albany,Dougherty,31.5500,-84.0612,Georgia,GA,31704
9,Albertville,Wright,45.2534,-93.6469,Minnesota,MN,55301
10,Red Lodge,Carbon,45.1965,-109.2688,Montana,MT,59068
11,Bridgewater,Aroostook,46.4222,-67.8415,Maine,ME,04735
12,Ashton,Spink,45.0465,-98.3973,South Dakota,SD,57424
13,Winchester,Franklin,35.1864,-86.1130,Tennessee,TN,37398
14,Putnamville,Putnam,39.5742,-86.8653,Indiana,IN,46170
15,Portland,Multnomah,45.5235,-122.6762,Oregon,OR,97286
16,Hillsdale,Columbia,42.1868,-73.5483,New York,NY,12529
17,Nashville,Howard,33.9576,-93.8707,Arkansas,AR,71852
18,Aulander,Bertie,36.1475,-77.1141,North Carolina,NC,27805
19,Waddell,Maricopa,33.5673,-112.4387,Arizona,AZ,85355
20,Northpoint,Indiana,40.9037,-79.1257,Pennsylvania,PA,15763
21,Okeechobee,Okeechobee,27.4203,-80.9454,Florida,FL,34972
22,Watkins Glen,Schuyler,42.3771,-76.9022,New York,NY,14891
23,Puyallup,Pierce,47.1284,-122.3219,Washington,WA,98373
24,Gentry,Gentry,40.3411,-94.4142,Missouri,MO,64453
25,Poestenkill,Rensselaer,42.6918,-73.5627,New York,NY,12140
26,Ihlen,Pipestone,43.8955,-96.3640,Minnesota,MN,56140
27,Copper Harbor,Keweenaw,47.4688,-87.8884,Michigan,MI,49918
28,North Canton,Stark,40.7989,-81.3784,Ohio,OH,44720
29,Lakeland,Polk,28.0720,-81.9609,Florida,FL,33805
...,...,...,...,...,...,...,...
170,Petersburg,Huntingdon,40.6030,-77.9984,Pennsylvania,PA,16669
171,Vero Beach,Indian River,27.5885,-80.3923,Florida,FL,32962
172,Skagway,Skagway-Hoonah-Angoon,59.4685,-135.3018,Alaska,AK,99840
173,Riddlesburg,Bedford,40.1620,-78.2545,Pennsylvania,PA,16672
174,Sound Beach,Suffolk,40.9567,-72.9742,New York,NY,11789
175,Garrett Park,Montgomery,39.0365,-77.0931,Maryland,MD,20896
176,Clinton,De Witt,40.1487,-88.9627,Illinois,IL,61727
177,Brantingham,Lewis,43.6887,-75.2921,New York,NY,13312
178,Roanoke,Roanoke (city),37.2717,-79.9392,Virginia,VA,24042
179,Moores Hill,Dearborn,39.0945,-85.0638,Indiana,IN,47032
180,Hansen,Twin Falls,42.5249,-114.2994,Idaho,ID,83334
181,Idleyld Park,Douglas,43.3237,-123.0240,Oregon,OR,97447
182,Aberdeen,Butler,37.2539,-86.6817,Kentucky,KY,42201
183,Albany,Albany,42.6526,-73.7562,New York,NY,12236
184,Brocton,Edgar,39.6923,-87.9263,Illinois,IL,61917
185,Farwell,Howard,41.2204,-98.6481,Nebraska,NE,68838
186,Nederland,Boulder,39.9703,-105.4813,Colorado,CO,80466
187,Wysox,Bradford,41.7826,-76.3834,Pennsylvania,PA,18854
188,Alexandria,City of Alexandria,38.8044,-77.0467,Virginia,VA,22320
189,Letts,Louisa,41.2930,-91.2040,Iowa,IA,52754
190,Highlands,Monmouth,40.4037,-73.9915,New Jersey,NJ,07732
191,Waynesfield,Auglaize,40.6072,-83.9585,Ohio,OH,45896
192,Topeka,Shawnee,39.0154,-95.7469,Kansas,KS,66614
193,Russian Mission,Kusilvak,61.7744,-161.3939,Alaska,AK,99657
194,Eloy,Pinal,32.7509,-111.5833,Arizona,AZ,85131
195,Intercession City,Osceola,28.2774,-81.5069,Florida,FL,33848
196,Meridian,Ada,43.6121,-116.3915,Idaho,ID,83680
197,Fremont,Alameda,37.5176,-121.9287,California,CA,94539
198,Albertson,Nassau,40.7703,-73.6514,New York,NY,11507
199,Fredonia,Ozaukee,43.4770,-87.9612,Wisconsin,WI,53021

In [9]:
cities_df.to_csv("random_cities.csv", index=False)