In [2]:
import tweepy
import json
import keys
from racist_terms import black
import pandas as pd

# get keys
consumer_key = keys.CONSUMER_KEY
consumer_secret = keys.CONSUMER_SECRET
access_token = keys.ACCESS_TOKEN
access_token_secret = keys.ACCESS_SECRET

#autheticate
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth, parser=tweepy.parsers.JSONParser(), wait_on_rate_limit = True, wait_on_rate_limit_notify = True)

#data lists
word = []
time = []
text = []
num_hashtags = []
hashtag_list = []
num_user_mentions = []
user_id = []
name = []
screen_name = []
account_creation_time = []
user_tweet_count = []
location = []
num_followers = []
num_following = []
num_retweets = []
num_favorites = []
in_reply_to = []

def search_request(search_term):
    for x in range(5):
        if x == 0:
            end_id = None
        try:
            response = api.search(search_term, lang = "en", count = 100, max_id = end_id)['statuses']
            for tweet in response:
                tweet_text = tweet['text']
                if search_term in tweet_text:
                    word.append(search_term)
                    time.append(tweet['created_at'])
                    text.append(tweet['text'])
                    num_hashtags_tweet = len(tweet['entities']['hashtags'])
                    num_hashtags.append(num_hashtags_tweet)
                    hashtags = []
                    if num_hashtags_tweet > 0:
                        for hastag_text in tweet['entities']['hashtags']:
                            hashtags.append(hastag_text['text'])
                    hashtag_list.append(hashtags)
                    num_user_mentions.append(tweet['entities']['user_mentions'])
                    user_id.append(tweet['user']['id'])
                    screen_name.append(tweet['user']['screen_name'])
                    name.append(tweet['user']['name'])
                    account_creation_time.append(tweet['user']['created_at'])
                    user_tweet_count.append(tweet['user']['statuses_count'])
                    location.append(tweet['user']['location']) 
                    num_followers.append(tweet['user']['followers_count'])
                    num_following.append(tweet['user']['friends_count'])
                    num_retweets.append(tweet['retweet_count'])
                    num_favorites.append(tweet["favorite_count"])  
                    in_reply_to.append(tweet["in_reply_to_user_id"])  
            end_id = response[-1]['id'] - 1
        except: 
            print('Error on word: %s' % (search_term))

for term in black:
    slur = term.lower()
    search_request(slur)
    print("Results Total after %s: %s" % (term, len(word)))

Error on word: banjo lips
Error on word: banjo lips
Error on word: banjo lips
Error on word: banjo lips
Results Total after Banjo Lips: 0
Error on word: biscuit lip
Error on word: biscuit lip
Error on word: biscuit lip
Results Total after Biscuit Lip: 0
Results Total after Blackie: 68
Error on word: bo-bo
Error on word: bo-bo
Error on word: bo-bo
Error on word: bo-bo
Results Total after Bo-Bo: 83
Error on word: bonky
Error on word: bonky
Error on word: bonky
Error on word: bonky
Results Total after Bonky: 109
Error on word: boogat
Error on word: boogat
Error on word: boogat
Error on word: boogat
Results Total after Boogat: 110
Results Total after Boogie: 205
Results Total after Boon: 488
Results Total after Bumper Lips: 490
Error on word: buppie
Error on word: buppie
Error on word: buppie
Error on word: buppie
Results Total after Buppie: 494
Error on word: camel lips
Error on word: camel lips
Error on word: camel lips
Error on word: camel lips
Results Total after Camel Lips: 496
Error on word: chain dragger
Error on word: chain dragger
Error on word: chain dragger
Error on word: chain dragger
Results Total after Chain Dragger: 498
Error on word: chicken bandit
Error on word: chicken bandit
Error on word: chicken bandit
Results Total after Chicken Bandit: 498
Error on word: cliff ape
Error on word: cliff ape
Error on word: cliff ape
Error on word: cliff ape
Results Total after Cliff Ape: 498
Results Total after Coon: 752
Error on word: cotton-picker
Error on word: cotton-picker
Error on word: cotton-picker
Results Total after Cotton-Picker: 755
Error on word: curb-biter
Error on word: curb-biter
Error on word: curb-biter
Error on word: curb-biter
Results Total after Curb-Biter: 755
Results Total after Darkie: 882
Error on word: field nigger
Error on word: field nigger
Error on word: field nigger
Results Total after Field Nigger: 898
Error on word: ghetto hamster
Error on word: ghetto hamster
Error on word: ghetto hamster
Error on word: ghetto hamster
Error on word: ghetto hamster
Results Total after Ghetto Hamster: 898
Error on word: ghetto monkey
Error on word: ghetto monkey
Error on word: ghetto monkey
Error on word: ghetto monkey
Results Total after Ghetto Monkey: 901
Error on word: guttermonkey
Error on word: guttermonkey
Error on word: guttermonkey
Error on word: guttermonkey
Error on word: guttermonkey
Results Total after Guttermonkey: 901
Results Total after House Nigger: 1336
Results Total after Hutch: 1415
Results Total after Jig: 1685
Results Total after Jigaboo: 1954
Results Total after Jigga: 2029
Error on word: jungle bunny
Error on word: jungle bunny
Error on word: jungle bunny
Error on word: jungle bunny
Results Total after Jungle Bunny: 2048
Error on word: knuckle-dragger
Results Total after Knuckle-Dragger: 2072
Error on word: liver lips
Error on word: liver lips
Error on word: liver lips
Error on word: liver lips
Results Total after Liver Lips: 2085
Error on word: liverlips
Error on word: liverlips
Error on word: liverlips
Error on word: liverlips
Results Total after Liverlips: 2085
Error on word: magila gorilla
Error on word: magila gorilla
Error on word: magila gorilla
Error on word: magila gorilla
Error on word: magila gorilla
Results Total after Magila Gorilla: 2085
Results Total after Mammy: 2415
Error on word: monkeyboy
Results Total after Monkeyboy: 2452
Error on word: muffin-head
Results Total after Muffin-head: 2453
Error on word: mulunyan
Error on word: mulunyan
Error on word: mulunyan
Error on word: mulunyan
Error on word: mulunyan
Results Total after Mulunyan: 2453
Rate limit reached. Sleeping for: 773
Error on word: n'er
Results Total after N'er: 2455
Results Total after Nappy Head: 2669
Results Total after Negress: 2897
Results Total after Negro: 3052
Results Total after Negroid: 3181
Results Total after Nigger: 3580
Error on word: niggerachi
Error on word: niggerachi
Error on word: niggerachi
Error on word: niggerachi
Results Total after Niggerachi: 3582
Error on word: niggerette
Error on word: niggerette
Error on word: niggerette
Error on word: niggerette
Results Total after Niggerette: 3584
Error on word: niggerino
Error on word: niggerino
Error on word: niggerino
Error on word: niggerino
Results Total after Niggerino: 3588
Results Total after Nigglet: 3877
Results Total after Nigra: 4156
Error on word: patio primate
Error on word: patio primate
Error on word: patio primate
Error on word: patio primate
Error on word: patio primate
Results Total after Patio Primate: 4156
Error on word: point-six
Error on word: point-six
Error on word: point-six
Error on word: point-six
Error on word: point-six
Results Total after Point-Six: 4156
Error on word: porch monkey
Results Total after Porch Monkey: 4350
Error on word: pube head
Error on word: pube head
Error on word: pube head
Results Total after Pube Head: 4363
Results Total after Rope-Head: 4363
Error on word: shvatsa
Error on word: shvatsa
Error on word: shvatsa
Error on word: shvatsa
Error on word: shvatsa
Results Total after Shvatsa: 4363
Error on word: shvooga
Error on word: shvooga
Error on word: shvooga
Error on word: shvooga
Error on word: shvooga
Results Total after Shvooga: 4363
Results Total after Spade: 4541
Error on word: spear-chucker
Error on word: spear-chucker
Error on word: spear-chucker
Error on word: spear-chucker
Results Total after Spear-Chucker: 4542
Results Total after Spook: 4810
Error on word: strap hangers
Error on word: strap hangers
Error on word: strap hangers
Error on word: strap hangers
Results Total after Strap Hangers: 4812
Error on word: swamp donkey
Error on word: swamp donkey
Error on word: swamp donkey
Results Total after Swamp Donkey: 4875
Error on word: swamper
Results Total after Swamper: 5023
Results Total after Thick Lips: 5101
Error on word: tutsoon
Error on word: tutsoon
Error on word: tutsoon
Error on word: tutsoon
Error on word: tutsoon
Results Total after Tutsoon: 5101
Error on word: unemployus africanus
Error on word: unemployus africanus
Error on word: unemployus africanus
Error on word: unemployus africanus
Error on word: unemployus africanus
Results Total after Unemployus Africanus: 5101
Error on word: velcro-head
Error on word: velcro-head
Error on word: velcro-head
Error on word: velcro-head
Results Total after Velcro-head: 5101
Error on word: welfare monkey
Error on word: welfare monkey
Error on word: welfare monkey
Error on word: welfare monkey
Results Total after Welfare Monkey: 5102
Error on word: yard ape
Error on word: yard ape
Error on word: yard ape
Error on word: yard ape
Results Total after Yard Ape: 5121
Error on word: zigaboo
Error on word: zigaboo
Error on word: zigaboo
Error on word: zigaboo
Results Total after Zigaboo: 5121
Error on word: zoo ape
Error on word: zoo ape
Error on word: zoo ape
Results Total after Zoo Ape: 5123

In [ ]:
word = []
time = []
text = []
num_hashtags = []
hashtag_list = []
num_user_mentions = []
user_id = []
name = []
screen_name = []
account_creation_time = []
user_tweet_count = []
location = []
num_followers = []
num_following = []
num_retweets = []
num_favorites = []
in_reply_to = []

In [5]:
racist_black_df = pd.DataFrame({
    "term": word,
    "time": time,
    "tweet": text,
    "# of hastags": num_hashtags,
    "# of mentions": num_user_mentions,
    "screen name": screen_name,
    "user id": user_id,
    "name": name,
    "account creation date": account_creation_time,
    "number of account tweets": user_tweet_count,
    "location": location,
    "# followers": num_followers,
    "# following": num_following,
    "# retweets of tweet": num_retweets,
    "# favorite of tweet": num_favorites,
    "in reply to": in_reply_to
})

In [6]:
len(racist_black_df)

5123

In [7]:
racist_black_df.head(10)

,# favorite of tweet,# followers,# following,# of hastags,# of mentions,# retweets of tweet,account creation date,in reply to,location,name,number of account tweets,screen name,term,time,tweet,user id
0,4,320,233,0,"[{'screen_name': 'BlackieWFangs', 'name': 'Bla...",0,Wed Feb 18 12:52:03 +0000 2009,7.536555e+17,,Phil,14360,PW0273,blackie,Fri Sep 22 18:53:47 +0000 2017,@BlackieWFangs @BlankPetra @jimjoneskoolai2 @A...,21192516
1,0,530,474,0,[],0,Mon Dec 26 22:11:39 +0000 2016,NaN,Malaysia,Kopi Panas,5108,hash_1993,blackie,Fri Sep 22 18:50:30 +0000 2017,I miss my blackie 🙀 https://t.co/Beqo8InTuR,813507594769825793
2,0,1219,281,0,"[{'screen_name': 'issa_blackie', 'name': 'Blac...",0,Wed Dec 07 08:44:07 +0000 2016,5.485077e+08,"Nairobi, Kenya",Valentine Kamau,4918,nimu_kamau,blackie,Fri Sep 22 18:11:06 +0000 2017,@issa_blackie That was my second thought 😂😂😂,806419001303855104
3,0,1219,281,0,"[{'screen_name': 'issa_blackie', 'name': 'Blac...",0,Wed Dec 07 08:44:07 +0000 2016,5.485077e+08,"Nairobi, Kenya",Valentine Kamau,4918,nimu_kamau,blackie,Fri Sep 22 18:10:21 +0000 2017,"@issa_blackie 😂😂😂😂😂😂You’re bored,Sindio??",806419001303855104
4,0,2518,5001,1,"[{'screen_name': 'caitlin_blackie', 'name': 'C...",0,Sun Mar 09 02:48:19 +0000 2014,3.133266e+09,United Kingdom,Jake Smith,15707,JakeSmi07598801,blackie,Fri Sep 22 17:06:04 +0000 2017,@caitlin_blackie @katie_shepherdd sorry girls ...,2379691897
5,0,223,164,0,"[{'screen_name': 'Campuzano60', 'name': 'Gabri...",1,Sun Jun 26 04:15:19 +0000 2011,NaN,"Tucson, AZ",Albert Campuzano,6760,LBZbeEasy,blackie,Fri Sep 22 17:02:32 +0000 2017,RT @Campuzano60: Anyone else have a dog named ...,324177736
6,0,43,365,2,"[{'screen_name': 'blackieschool', 'name': 'Bla...",2,Sat Oct 23 23:14:46 +0000 2010,NaN,"Alberta,Canada",Michael Stanford,29,stanfordmike26,blackie,Fri Sep 22 16:38:50 +0000 2017,RT @blackieschool: Blackie mid schoolers fabri...,206874300
7,1,3485,1985,0,"[{'screen_name': 'childishmari', 'name': 'cozy...",1,Wed Feb 02 16:50:27 +0000 2011,2.547546e+08,jiggin on a boo,la quica,42801,LYNTHEKILLER,blackie,Fri Sep 22 16:18:22 +0000 2017,@childishmari happy birthday blackie ❤️ love y...,246352430
8,0,452,231,0,"[{'screen_name': '_TheKP', 'name': 'Life Of KP...",0,Sat Nov 24 05:53:08 +0000 2012,6.134585e+08,Nairobi,The Story of C.K.,3655,CollinsMwangi3,blackie,Fri Sep 22 15:49:39 +0000 2017,@_TheKP @issa_blackie 😅😅\nWho is @issa_blackie...,967443716
9,0,200,151,0,[],0,Sat Aug 15 06:18:20 +0000 2009,NaN,"Cheyenne, Wy",Casey Nath,2217,caseystadel,blackie,Fri Sep 22 15:34:58 +0000 2017,This is blackie. https://t.co/JPkwKeIrTb,65842792

In [8]:
racist_black_df.to_csv('black_racist_tweets.csv')