In [7]:
import plotly.plotly as py
import pandas as pd

In [8]:
import plotly 
plotly.tools.set_credentials_file(username='racquesta', api_key='mEcy6kAYKdM15kgu2r7Y')

In [9]:
state_count = pd.read_csv('normalized_counts.csv')

In [10]:
state_count.head()

,Unnamed: 0,State,Total Population,State Abbr,black,jews,muslim,norm_black,norm_jewish,norm_muslim,total_count,total_norm
0,0,Alabama,4863300,AL,1.0,1.0,4.0,0.000021,0.000021,0.000082,6.0,0.000123
1,1,Alaska,741894,AK,1.0,0.0,1.0,0.000135,0.000000,0.000135,2.0,0.000270
2,2,Arizona,6931071,AZ,1.0,0.0,4.0,0.000014,0.000000,0.000058,5.0,0.000072
3,3,Arkansas,2988248,AR,3.0,1.0,3.0,0.000100,0.000033,0.000100,7.0,0.000234
4,4,California,39250017,CA,30.0,31.0,17.0,0.000076,0.000079,0.000043,78.0,0.000199

In [19]:
state_count.sort_values('total_norm', ascending = False)

,Unnamed: 0,State,Total Population,State Abbr,black,jews,muslim,norm_black,norm_jewish,norm_muslim,total_count,total_norm
8,8,District of Columbia,681170,DC,8.0,10.0,1.0,0.001174,0.001468,0.000147,19.0,0.002789
40,45,Vermont,624594,VT,2.0,1.0,0.0,0.000320,0.000160,0.000000,3.0,0.000480
22,24,Mississippi,2988726,MS,5.0,1.0,7.0,0.000167,0.000033,0.000234,13.0,0.000435
7,7,Delaware,952065,DE,3.0,1.0,0.0,0.000315,0.000105,0.000000,4.0,0.000420
20,22,Michigan,9928300,MI,16.0,9.0,7.0,0.000161,0.000091,0.000071,32.0,0.000322
35,39,Rhode Island,1056426,RI,1.0,1.0,1.0,0.000095,0.000095,0.000095,3.0,0.000284
28,32,New York,19745289,NY,20.0,22.0,13.0,0.000101,0.000111,0.000066,55.0,0.000279
16,18,Louisiana,4681666,LA,8.0,2.0,3.0,0.000171,0.000043,0.000064,13.0,0.000278
1,1,Alaska,741894,AK,1.0,0.0,1.0,0.000135,0.000000,0.000135,2.0,0.000270
36,40,South Carolina,4961119,SC,4.0,5.0,3.0,0.000081,0.000101,0.000060,12.0,0.000242
25,28,Nevada,2940058,NV,4.0,1.0,2.0,0.000136,0.000034,0.000068,7.0,0.000238
38,43,Texas,27862596,TX,21.0,27.0,18.0,0.000075,0.000097,0.000065,66.0,0.000237
3,3,Arkansas,2988248,AR,3.0,1.0,3.0,0.000100,0.000033,0.000100,7.0,0.000234
32,36,Oklahoma,3923561,OK,4.0,2.0,3.0,0.000102,0.000051,0.000076,9.0,0.000229
9,9,Florida,20612439,FL,19.0,13.0,14.0,0.000092,0.000063,0.000068,46.0,0.000223
18,20,Maryland,6016447,MD,6.0,5.0,1.0,0.000100,0.000083,0.000017,12.0,0.000199
4,4,California,39250017,CA,30.0,31.0,17.0,0.000076,0.000079,0.000043,78.0,0.000199
42,47,Washington,7288000,WA,4.0,5.0,5.0,0.000055,0.000069,0.000069,14.0,0.000192
10,10,Georgia,10310371,GA,10.0,5.0,4.0,0.000097,0.000048,0.000039,19.0,0.000184
21,23,Minnesota,5519952,MN,3.0,5.0,2.0,0.000054,0.000091,0.000036,10.0,0.000181
34,38,Pennsylvania,12784227,PA,10.0,8.0,5.0,0.000078,0.000063,0.000039,23.0,0.000180
45,50,Wyoming,585501,WY,0.0,0.0,1.0,0.000000,0.000000,0.000171,1.0,0.000171
37,42,Tennessee,6651194,TN,3.0,4.0,4.0,0.000045,0.000060,0.000060,11.0,0.000165
23,25,Missouri,6093000,MO,7.0,2.0,1.0,0.000115,0.000033,0.000016,10.0,0.000164
19,21,Massachusetts,6811779,MA,3.0,5.0,3.0,0.000044,0.000073,0.000044,11.0,0.000161
15,17,Kentucky,4436974,KY,2.0,3.0,2.0,0.000045,0.000068,0.000045,7.0,0.000158
29,33,North Carolina,10146788,NC,8.0,3.0,5.0,0.000079,0.000030,0.000049,16.0,0.000158
26,30,New Jersey,8944469,NJ,7.0,5.0,2.0,0.000078,0.000056,0.000022,14.0,0.000157
41,46,Virginia,8411808,VA,3.0,6.0,4.0,0.000036,0.000071,0.000048,13.0,0.000155
12,13,Illinois,12801539,IL,11.0,2.0,6.0,0.000086,0.000016,0.000047,19.0,0.000148
33,37,Oregon,4093465,OR,1.0,3.0,2.0,0.000024,0.000073,0.000049,6.0,0.000147
27,31,New Mexico,2081015,NM,0.0,1.0,2.0,0.000000,0.000048,0.000096,3.0,0.000144
6,6,Connecticut,3576452,CT,2.0,2.0,1.0,0.000056,0.000056,0.000028,5.0,0.000140
14,16,Kansas,2907289,KS,1.0,2.0,1.0,0.000034,0.000069,0.000034,4.0,0.000138
30,34,North Dakota,757953,ND,0.0,1.0,0.0,0.000000,0.000132,0.000000,1.0,0.000132
39,44,Utah,3051217,UT,3.0,1.0,0.0,0.000098,0.000033,0.000000,4.0,0.000131
5,5,Colorado,5540545,CO,4.0,0.0,3.0,0.000072,0.000000,0.000054,7.0,0.000126
0,0,Alabama,4863300,AL,1.0,1.0,4.0,0.000021,0.000021,0.000082,6.0,0.000123
43,48,West Virginia,1831102,WV,1.0,0.0,1.0,0.000055,0.000000,0.000055,2.0,0.000109
13,14,Indiana,6633053,IN,1.0,3.0,3.0,0.000015,0.000045,0.000045,7.0,0.000106
24,27,Nebraska,1907116,NE,0.0,0.0,2.0,0.000000,0.000000,0.000105,2.0,0.000105
31,35,Ohio,11614373,OH,4.0,4.0,4.0,0.000034,0.000034,0.000034,12.0,0.000103
17,19,Maine,1331479,ME,1.0,0.0,0.0,0.000075,0.000000,0.000000,1.0,0.000075
2,2,Arizona,6931071,AZ,1.0,0.0,4.0,0.000014,0.000000,0.000058,5.0,0.000072
11,12,Idaho,1683140,ID,0.0,1.0,0.0,0.000000,0.000059,0.000000,1.0,0.000059
44,49,Wisconsin,5778709,WI,2.0,1.0,0.0,0.000035,0.000017,0.000000,3.0,0.000052

In [11]:
data = [ dict(
        type='choropleth',
        autocolorscale = False,
        locations = state_count['State Abbr'],
        z = state_count['total_norm'],
        locationmode = 'USA-states',
        #text = df['text'],
        marker = dict(
            line = dict (
                color = 'rgb(255,255,255)',
                width = 2
            ) ),
        colorbar = dict(
            title = "Millions USD")
        ) ]

In [12]:
layout = dict(
        title = '2011 US Agriculture Exports by State<br>(Hover for breakdown)',
        geo = dict(
            scope='usa',
            projection=dict( type='albers usa' ),
            showlakes = True,
            lakecolor = 'rgb(255, 255, 255)'),
             )

In [15]:
fig = dict( data=data, layout=layout )
#url = py.offline.iplot(fig, filename='d3-cloropleth-map')
#print(url)
py.image.save_as(fig, filename='a-simple-plot.png')